### ISSUE TITLE
繁化姬不能使用

### ISSUE THREAD

**Issue by tkh0395** [maple3142/ebook-converter#17]
未知緣由導致了檔案轉換失敗。
若您是使用繁化姬轉換的，可能是因為檔案大小太大才失敗的，可考慮改用 OpenCC。

會不會是api更新了 
用了 ThanatosDi / EpubConv_Python 也是顯示 zhconvert Request error. status code: 429

**Comment by jfcherng** [comment]
[429 Too Many Requests](https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Status/429)

**Comment by tkh0395** [comment]
> [429 Too Many Requests](https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Status/429)

i dont think its on my end tho, I tried it once today and it still shows that

**Comment by tkh0395** [comment]
issue solved itself by time i guess
