### ISSUE TITLE
epub/txt 電子書繁簡轉換 無法使用

### ISSUE THREAD

**Issue by Shan404nofound** [maple3142/ebook-converter#26]
顯示錯誤訊息
Error: ENOSPC: no space left on device, open '/app/server/uploads/b7543981158a7c6fabbc036ec9d09873'

**Comment by maple3142** [comment]
應該修好了

**Comment by Shan404nofound** [comment]
您好，感謝您迅速的處理，但不知是否連結有誤，把txt檔放入“Txt 檔案(繁化姬)“處進行轉換時，出現了以下訊息：
檔案類型並非 application/epub+zip

**Comment by maple3142** [comment]
修了

**Comment by Shan404nofound** [comment]
感謝您，處理的速度真的很快，epub/txt 電子書繁簡轉換使用做得很棒，功能強大又方便。
