### ISSUE TITLE
未知緣由導緻了檔案轉換失敗。 但是我用OpenCC

### ISSUE THREAD

**Issue by PiauTW** [maple3142/ebook-converter#4]
原檔案名: 0.txt
未知緣由導緻了檔案轉換失敗。
若您是使用繁化姬轉換的，可能是因為檔案大小太大才失敗的，可考慮改用 OpenCC。

可是我用就是opencc :(

**Comment by maple3142** [comment]
請提供檔案

**Comment by maple3142** [comment]
現在應該沒這問題了
